### PR TITLE
fix: parse provided payloads before replacing templated variables

### LINKED ISSUE #427: Templated payload variables are replaced before the payload is parsed
```
runs:
  using: "composite"
  steps:
    - name: Post a message in a channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: "${{ env.SLACK_WEBHOOK_URL }}"
        webhook-type: incoming-webhook
        # See: https://api.slack.com/reference/messaging/attachments
        payload: |
          attachments:
            - color: "${{ inputs.status == 'success' && 'good' || inputs.status == 'failure' && 'danger' || '#808080' }}"
              pretext: "${{ inputs.text }}"
              title: "Build Status: ${{ inputs.status }}"
              title_link: "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
              fields:
                - title: "Author"
                  value: "${{ github.event.head_commit.author.name }}"
                  short: true
                - title: "Repository"
                  value: "<${{ github.event.repository.html_url }}|${{ github.event.repository.full_name }}>"
                  short: true
                - title: "Head commit"
                  value: "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
                  short: false
```

With the above call to `slack-github-action` I ran into a parsing issue. For certain commit messages, the followed error occured.

```
file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:93
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload
    at Content.getContentPayload (file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:93:1)
    at Content.get (file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:28:1)
    at new Config (file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/config.js:115:1)
    at send (file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/send.js:13:1)
    at file:///home/runner/_work/_actions/slackapi/slack-github-action/v2.0.0/src/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

After trying a bunch of commit messages, I could simplify the string that would cause the above error to the following

`\n---\n`

This string would be inserted into `${{ github.event.head_commit.message }}>`

This is a YAML-directive. Which is weird, because the variables do not exist at YAML-level.

**Code**

I then further tracked it down to the following code.

First, it translates the variables to their values. Here

https://github.com/slackapi/slack-github-action/blob/d07fadf6b91dd644931ee3b68600be76f0c6917c/src/content.js#L121

And

https://github.com/slackapi/slack-github-action/blob/d07fadf6b91dd644931ee3b68600be76f0c6917c/src/content.js#L155-L166

It tries to parse the payload parameter as YAML

https://github.com/slackapi/slack-github-action/blob/d07fadf6b91dd644931ee3b68600be76f0c6917c/src/content.js#L64-L77

If that fails, it tries to parse the payload parameter as JSON

https://github.com/slackapi/slack-github-action/blob/d07fadf6b91dd644931ee3b68600be76f0c6917c/src/content.js#L78-L100

If that fails, it exits.

**What I think is the problem**

The problem I see with this however, is that the order is incorrect. What is being done is:
- Change variables to their output value.
- Parse Yaml

What should be done is:
- Parse Yaml
- Change variables to their output value

This might also have security implications, since the inserted variables could modify the yaml document. I know to little about YAML and use cases for `slack-github-action` to be sure.

### PR DESCRIPTION
**Pull request by zimeg**
### Summary

This PR parses the provided payload **before** replacing templated variables to avoid erroneous parsings from perhaps variables with linebreaks - fixes #427.

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

File: src/content.js [hunk 1]
```diff
@@ -148,20 +149,32 @@ export default class Content {
...
-    if (!config.inputs.payloadTemplated) {
-      return input;
+  templatize(input) {
+    if (Array.isArray(input)) {
+      return input.map((v) => this.templatize(v));
+    }
+    if (input && typeof input === "object") {
+      /**
+       * @type {any}
+       */
```
Comment (WilliamBergamin) [inline src/content.js:163]: Not very familiar with this typing format in JS doc but would we want to be more specific but using a `Record<string, string>`?

File: test/content.spec.js [hunk 2]
```diff
@@ -257,14 +295,61 @@ describe("content", () => {
       mocks.fs.readFileSync
```
Comment (WilliamBergamin) [inline test/content.spec.js:295]: These tests are pretty sweet 💯  should we also add a case with `array` options?

But this might be out of scope for this project because these elements mainly appear in interactive components like static multi-selects 

Example
```json
[
	{
		"type": "section",
		"block_id": "section678",
		"text": {
			"type": "mrkdwn",
			"text": "Pick items from the list"
		},
		"accessory": {
			"action_id": "text1234",
			"type": "multi_static_select",
			"placeholder": {
				"type": "plain_text",
				"text": "Select items"
			},
			"options": [
				{
					"text": {
						"type": "plain_text",
						"text": "*this is plain_text text*"
					},
					"value": "value-0"
				},
				{
					"text": {
						"type": "plain_text",
						"text": "*this is plain_text text*"
					},
					"value": "value-2"
				}
			]
		}
	}
]
```

**Review by WilliamBergamin — APPROVED** [review]
Sweet 🚀 this looks like a great fix!

Left a few non blocking comments

File: src/content.js [hunk 3]
```diff
@@ -148,20 +149,32 @@ export default class Content {
   }
 
   /**
-   * Replace templated variables in the provided content if requested.
-   * @param {Config} config
-   * @param {string} input - The initial value of the content.
-   * @returns {string} Content with templatized variables replaced.
+   * Replace templated variables in the provided content as requested.
+   * @param {unknown} input - The initial value of the content.
+   * @returns {unknown} Content with templatized variables replaced.
```
[the remark this answers is not in the document]
Comment (zimeg) [reply src/content.js:154]: @WilliamBergamin Haha I started writing all possible types but also found that testing the actual behavior is more useful here 😉

File: test/content.spec.js (hunk 2 above)
Comment (zimeg) [reply test/content.spec.js:295]: @WilliamBergamin This is a fascinating suggestion! 🧠 ✨

Right now we have a `blocks` array but that's at the top-level and doesn't promise we recurse as expected 🤓

I hadn't thought about sending interactive blocks from a GitHub Action but I'm now so curious about how this might connect with the same app listening for events in the workspace otherwise!

Comment (zimeg) [reply test/content.spec.js:378]: A similar example is added in https://github.com/slackapi/slack-github-action/pull/449/commits/5c48fcffb2efad4481b75a86fb16af74af93e16c to confirm the templated replacement behavior 🚀

**Review by WilliamBergamin — APPROVED** [review]
Awesome work on the array support 💯

**Review by mwbrooks — APPROVED** [review]
