### PR TITLE
fix: avoid erroring if conflicting techniques are set from environment variables

### LINKED ISSUE #373: Shared environment variables can cause multiple techniques to match which errors
### Description

Setting either the `SLACK_TOKEN` or `SLACK_WEBHOOK_URL` environment variables for all steps in a workflow, then creating a step with an opposite technique, causes the step to fail despite the input seeming correct. Noted here: https://github.com/slackapi/slack-github-action/issues/372#issuecomment-2518975584

### What type of issue is this?

- [x] bug

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Steps to reproduce:

```yaml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Start a workflow with a webhook trigger
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          webhook: ${{ secrets.SLACK_WEBHOOK_TRIGGER }}
          webhook-type: webhook-trigger
          payload: |
            author: ${{ github.event.sender.login }}
```

#### Expected result:

The provided `webhook` input to be used!

#### Actual result:

```
SlackError: Invalid input! Either the token or webhook is required - not both.
```

### PR DESCRIPTION
**Pull request by zimeg**
### Summary

This PR allows both environment variables `SLACK_TOKEN` and `SLACK_WEBHOOK_URL` to exist in a workflow without causing steps to error due to an undefined technique! Fixes #373.

### Reviewers

Add the following to the workflow in `develop.yml` before running with `npm run dev`:

```diff
+   env:
+     SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    runs-on: ubuntu-latest
```

This should error before the change is applied but not after!

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -133,29 +149,20 @@ export default class Config {
         );
     }
     switch (true) {
-      case !!this.inputs.token && !!this.inputs.webhook:
-        core.debug(
-          "Setting the provided token and webhook as secret variables.",
-        );
-        core.setSecret(this.inputs.token);
-        core.setSecret(this.inputs.webhook);
+      case !!core.getInput("token") && !!core.getInput("webhook"):
```
Comment (zimeg) [inline src/config.js:152]: This prevents adding both `token` and `webhook` as inputs using `with` while still allowing both environment variables!

**Review by seratch — APPROVED** [review]
I haven't verified the behavior but the code changes look good to me and there is nothing to suggest so far. This is pretty cool!

File: src/config.js [hunk 2]
```diff
@@ -133,29 +149,20 @@ export default class Config {
...
         throw new SlackError(
           core,
           "Invalid input! Either the token or webhook is required - not both.",
         );
-      case !!this.inputs.token:
-        core.debug("Setting the provided token as a secret variable.");
-        core.setSecret(this.inputs.token);
-        if (!this.inputs.method) {
+      case !!this.inputs.method:
+        if (!this.inputs.token) {
```
Comment (zimeg) [inline src/config.js:158]: Special care was taken in flipping these cases with wording since we can't assume a set `this.inputs.token` means that technique is being used.

Instead, I think we must check for a `method` instead of `token`, and always check `method` before `webhook` 🤔

File: src/send.js [hunk 3]
```diff
@@ -29,7 +29,7 @@ export default async function send(core) {
  */
 async function post(config) {
   switch (true) {
-    case !!config.inputs.token:
+    case !!config.inputs.method:
```
Comment (zimeg) [inline src/send.js:32]: IMO an important change that might've been missed without testing a bit! Before changes, an environment variable might've set this and caused this `case` to run despite possible inputs preferring the `webhook`.

This is covered and confirmed in the `send.spec.js` tests!

**Review by zimeg — COMMENTED** [review]
@seratch Thank you once again for such a fast review! I'll test this a few more times before merging, but will merge once things are feeling good.

Also leaving a few notes on some of the stranger changes, but am hopeful that tests cover the expected behaviors well 🙏

**Comment by zimeg** [comment]
🚢 💨  Merging now! But going to hold off on an immediate release with hopes of landing a few docs updates before the next tag. Planning to make those changes soon in another PR- 🫡
